# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63d915407c8d956895ea650ae7906e9ca9234a74402979b4620ef46ff2d6aa04a4d806de64a61889b9b1b495561d2e469abf819b0132f51a75c2e0c023b7c19f

test:
  secret_key_base: 91e57a5face7eda446b195665766606442c0bb7f1dfe3db6ec47b39bffb95a247dc112b8b3469892d8149781f834eaff4f60c10905ee179c4c3a3cc64a8878d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
